name: Create Release Version

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "int or prod"
        required: true
        default: "int"
      based_on_version:
        description: "tag"
        required: true
        default: "default"
      release_type:
        description: "major, minor or patch"
        required: false

jobs:
  create_release_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Get Release Version
        id: get_release_version
        run: |
          git config --global user.email "team-odm@valtech-mobility.com"
          git config --global user.name "Team ODM"
          release_version=$(python ./increment_new_version.py \
                                --stage ${{ inputs.stage }} \
                                --based_on_version ${{ inputs.based_on_version }} \
                                --release_type ${{ inputs.release_type }})
          echo "----------$release_version----------------"                      
          echo "release_version='$release_version'" >> $GITHUB_OUTPUT          
      
      - name: Release Note
        run: |
          echo "${{ steps.get_release_version.outputs.release_version }}" > release-note.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_release_version.outputs.release_version }}
          release_name: "Release ${{ steps.get_release_version.outputs.release_version }}"
          body: |
            This is the release tag description.
          draft: false
          prerelease: false

      - name: Commit changes
        run: |
          git commit -a -m "Update the release note for ${{ steps.get_release_version.outputs.release_version }}"
          git push
