name: Create Release Version

on:
  push:
    branches:
      - master

jobs:
  create_release_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get Release Version
        id: get_release_version
        run: |
          release_version="v1.0.13"
          echo "::set-output name=my_output::$release_version"
          
      
      - name: Release Note
        run: |
          echo "${{ steps.get_release_version.my_output }}" > release-note.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_release_version.my_output }}
          release_name: "Release ${{ steps.get_release_version.my_output }}"
          body: |
            This is the release tag description.
          draft: false
          prerelease: false

      - name: Commit changes
        run: |
          git config --global user.email "team-odm@valtech-mobility.com"
          git config --global user.name "Team ODM"
          git commit -a -m "Update the release note for $release_version"
          git push
