name: Create Release Version

on:
  push:
    branches:
      - master

jobs:
  create_release_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Release Note
        run: |
          release_version="v1.0.7"
          echo "$release_version" > release-note.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "$release_version"
          release_name: Release "$release_version"
          body: |
            This is the release tag description.
          draft: false
          prerelease: false

      - name: Commit changes
        run: |
          git config --global user.email "team-odm@valtech-mobility.com"
          git config --global user.name "Team ODM"
          git commit -a -m "Update the release note for "$release_version""
          git push
