name: Create Release Version

on:
  push:
    branches:
      - master

jobs:
  create_release_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Release Note
        run: |
          echo "v1.0.2" > release-note.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.2
          release_name: Release v1.0.2
          body: |
            This is the release tag description.
          draft: false
          prerelease: false

      - name: Get Release Tag
        run: echo "The release tag is ${{ steps.create_release.outputs.tag }}"
